import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <link rel="icon" href="https://nextjs.org/favicon.ico" />
      </header>
      <body
        style={{
          backgroundImage: 'url("/images/forest.jpg")',
          backgroundSize: "cover",
        }}
      >
        {children}
      </body>
    </html>
  );
}
