import "./globals.css";
import NextAuthSessionProvider from "./nextAuth/nextAuthSessionProvider";
export const metadata = {
  title: "Next JS Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextAuthSessionProvider>
        {children}
      </NextAuthSessionProvider>
      </body>
    </html>
  );
}
