import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: 'url("/images/forest.jpg")',
          backgroundSize: "cover",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",

        }}
      >
        {children}
      </body>
    </html>
  );
}
